<?php
/**
 * Template for the Price History Chart block.
 * 
 * This file renders the HTML container for the price history chart.
 * The actual chart is generated by JavaScript using Chart.js.
 */

// Prevent direct file access
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Get the ACF field value
$selected_product = get_field('selected_product');

// Ensure we have a valid product selected
if ( ! $selected_product || ! is_object( $selected_product ) || ! isset( $selected_product->ID ) ) {
	// In preview mode, show a placeholder
	if ( is_admin() && isset( $_GET['preview'] ) ) {
		echo '<div class="hft-price-history-placeholder">';
		echo '<p>' . esc_html__( 'Price History Chart: Please select a product.', 'housefresh-tools' ) . '</p>';
		echo '</div>';
	}
	// On frontend, show nothing if no product is selected
	return;
}

$product_id = $selected_product->ID;

// Quick check: Does this product have any tracked links with price history?
global $wpdb;
$tracked_links_table = $wpdb->prefix . 'hft_tracked_links';
$price_history_table = $wpdb->prefix . 'hft_price_history';

$has_price_history = $wpdb->get_var( $wpdb->prepare(
	"SELECT COUNT(ph.id) 
	 FROM {$price_history_table} ph 
	 INNER JOIN {$tracked_links_table} tl ON ph.tracked_link_id = tl.id 
	 WHERE tl.product_post_id = %d",
	$product_id
) );

// If no price history data, don't render anything on frontend
if ( ! $has_price_history && ! is_admin() ) {
	return;
}

// If in admin preview and no data, show placeholder
if ( ! $has_price_history && is_admin() ) {
	echo '<div class="hft-price-history-placeholder">';
	echo '<p>' . esc_html__( 'Price History Chart: No price history data available for this product yet.', 'housefresh-tools' ) . '</p>';
	echo '</div>';
	return;
}

// Generate unique block ID
$block_id = 'hft-price-history-' . uniqid();

// If we are on the frontend AND a product is selected AND it has price history data, output the container for JS.
?>
<div id="<?php echo esc_attr($block_id); ?>" 
	 class="hft-price-history-container is-loading" 
	 data-hft-product-id="<?php echo esc_attr((string)$product_id); ?>"
	 data-hft-block-id="<?php echo esc_attr($block_id); ?>">
	
	<div class="hft-price-history-header">
		<h3 class="hft-price-history-title"><?php esc_html_e( 'Price History', 'housefresh-tools' ); ?></h3>
	</div>
	
	<div class="hft-price-history-chart-wrapper is-loading">
		<canvas id="<?php echo esc_attr($block_id); ?>-chart" class="hft-price-history-chart"></canvas>
	</div>
	
	<div class="hft-price-stats-table is-loading">
		<table>
			<thead>
				<tr>
					<th>Retailer</th>
					<th>Lowest Ever</th>
					<th>Highest Ever</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="retailer-name"><div class="skeleton-cell"></div></td>
					<td class="price-cell">
						<div class="skeleton-cell"></div>
						<div class="skeleton-cell small"></div>
					</td>
					<td class="price-cell">
						<div class="skeleton-cell"></div>
						<div class="skeleton-cell small"></div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	
	<div class="hft-price-history-loading" style="display: none;">
		<?php esc_html_e( 'Loading price history...', 'housefresh-tools' ); ?>
	</div>
	
	<div class="hft-price-history-error" style="display: none;">
		<?php esc_html_e( 'Unable to load price history data.', 'housefresh-tools' ); ?>
	</div>
</div> 