<?php
/**
 * Single Tool Template - E-Scooter Laws Map
 *
 * Custom full-width template for the interactive US e-scooter laws map.
 * WordPress auto-selects this over single-tool.php for slug "escooter-laws-map".
 *
 * @package ERideHero
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

get_header();

$post_id   = get_the_ID();
$tool_slug = get_post_field( 'post_name', $post_id );

// Load and sort laws data
$json_path = get_theme_file_path( 'assets/data/laws.json' );
$laws_data = [];

if ( file_exists( $json_path ) ) {
    $json_contents = file_get_contents( $json_path );
    $laws_data     = json_decode( $json_contents, true ) ?: [];
    uasort( $laws_data, fn( $a, $b ) => strcmp( $a['name'] ?? '', $b['name'] ?? '' ) );
}
?>

<main id="main-content" class="tool-page">
    <div class="tool-layout">
        <div class="container">
            <!-- Title Row -->
            <div class="tool-title-row">
                <div class="tool-title-content">
                    <?php
                    erh_breadcrumb( [
                        [ 'label' => 'Tools', 'url' => get_post_type_archive_link( 'tool' ) ],
                        [ 'label' => get_the_title() ],
                    ] );
                    ?>
                    <h1 class="tool-title"><?php the_title(); ?></h1>
                    <?php if ( has_excerpt() ) : ?>
                        <p class="tool-description"><?php echo esc_html( get_the_excerpt() ); ?></p>
                    <?php endif; ?>
                </div>
            </div>

            <!-- Calculator container - triggers JS dispatcher -->
            <div class="laws-map" data-calculator="<?php echo esc_attr( $tool_slug ); ?>">

                <!-- Search -->
                <div class="search-container">
                    <input type="text" id="state-search" placeholder="Enter state name or abbreviation..." autocomplete="off">
                    <div id="suggestions-box"></div>
                </div>

                <!-- Map + Info Box -->
                <div id="map-container">
                    <div class="map-legend">
                        <div class="legend-item state-legal">
                            <span class="legend-color"></span>
                            <span class="legend-label">Legal</span>
                        </div>
                        <div class="legend-item state-conditional">
                            <span class="legend-color"></span>
                            <span class="legend-label">Varies by location</span>
                        </div>
                        <div class="legend-item state-prohibited">
                            <span class="legend-color"></span>
                            <span class="legend-label">Prohibited</span>
                        </div>
                    </div>

                    <?php get_template_part( 'template-parts/tools/laws-map-svg' ); ?>

                    <div id="info-box"></div>
                </div>

                <!-- State Details -->
                <div id="details-container">
                    <div class="details-content-column">
                        <?php foreach ( $laws_data as $state_id => $state_data ) : ?>
                            <?php
                            get_template_part( 'template-parts/tools/laws-map-state', null, [
                                'state_id'   => $state_id,
                                'state_data' => $state_data,
                            ] );
                            ?>
                        <?php endforeach; ?>
                    </div>

                    <aside class="details-toc-column">
                        <h3>State Details Index</h3>
                        <ul id="desktop-toc-list">
                            <!-- Generated by JS -->
                        </ul>
                    </aside>
                </div>

                <!-- Floating Buttons -->
                <button id="back-to-top-btn" class="floaty-btn" title="Go to top" aria-label="Go to top">
                    <svg><use xlink:href="#chevron"></use></svg>
                </button>
                <button id="toc-mobile-btn" class="floaty-btn" title="Open State Details Index" aria-label="Open State Details Index">
                    <svg viewBox="0 0 24 24" fill="currentColor"><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"></path></svg>
                </button>

                <!-- Mobile ToC Popup -->
                <div id="mobile-toc-popup" role="dialog" aria-modal="true" aria-labelledby="mobile-toc-title">
                    <div class="mobile-toc-header">
                        <h3 id="mobile-toc-title">State Details Index</h3>
                        <button class="close-mobile-toc" aria-label="Close index">&times;</button>
                    </div>
                    <ul id="mobile-toc-list">
                        <!-- Generated by JS -->
                    </ul>
                </div>

                <?php get_template_part( 'template-parts/tools/laws-map-icons' ); ?>

                <?php the_content(); ?>
            </div>
        </div>
    </div>
</main>

<?php
get_footer();
?>
<script>
window.erhData = window.erhData || {};
window.erhData.toolSlug = <?php echo wp_json_encode( $tool_slug ); ?>;
window.erhData.lawsData = <?php echo wp_json_encode( $laws_data ); ?>;
</script>
