<?php
/**
 * Product Sidebar
 *
 * @package ERideHero
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

$product_id    = get_the_ID();
$product_type  = get_field( 'product_type', $product_id ) ?: 'Electric Scooter';
$category      = \ERH\CategoryConfig::get_by_type( $product_type );
$archive_slug  = $category ? $category['archive_slug'] : 'e-scooters';
?>
<div class="sidebar-sticky">
    <!-- Table of Contents -->
    <div class="sidebar-toc">
        <h3 class="sidebar-toc-title"><?php esc_html_e( 'Contents', 'erh' ); ?></h3>
        <nav class="sidebar-toc-nav">
            <!-- TOC links will be generated by toc.js -->
        </nav>
    </div>

    <!-- Quick Actions -->
    <div class="sidebar-actions">
        <a href="#where-to-buy" class="btn btn-primary btn-block">
            <?php esc_html_e( 'Where to buy', 'erh' ); ?>
        </a>
        <button type="button" class="btn btn-secondary btn-block" data-modal-trigger="price-alert-modal">
            <?php erh_the_icon( 'bell' ); ?>
            <?php esc_html_e( 'Track price', 'erh' ); ?>
        </button>
        <a href="<?php echo esc_url( home_url( '/' . $archive_slug . '/compare/?add=' . $product_id ) ); ?>" class="btn btn-ghost btn-block">
            <?php erh_the_icon( 'grid' ); ?>
            <?php esc_html_e( 'Compare', 'erh' ); ?>
        </a>
    </div>

    <!-- Compare Widget -->
    <div class="sidebar-compare-widget">
        <h3 class="sidebar-compare-title"><?php esc_html_e( 'Compare with', 'erh' ); ?></h3>
        <div class="sidebar-compare-slots" data-compare-widget>
            <!-- Comparison slots populated by JS -->
        </div>
    </div>
</div>
