<?php
/**
 * Home: Comparison Section
 *
 * Head-to-head product comparison tool.
 * Loads products from comparison_products.json generated by cron.
 *
 * @package ERideHero
 */

// Prevent direct access
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Get the JSON URL for the comparison products
$upload_dir = wp_upload_dir();
$json_url   = $upload_dir['baseurl'] . '/comparison_products.json';
?>

<section class="comparison-section">
    <div class="container">
        <div class="comparison-card">
            <div class="comparison-card-bg" aria-hidden="true">
                <div class="comparison-orb"></div>
            </div>
            <div class="comparison-content">
                <header class="comparison-header">
                    <h2><?php esc_html_e( 'Compare electric rides head-to-head', 'erh' ); ?></h2>
                    <div class="comparison-category-pill" id="comparison-category-pill" aria-live="polite">
                        <span id="comparison-category-text"><?php esc_html_e( 'Showing e-scooters', 'erh' ); ?></span>
                        <button type="button" aria-label="<?php esc_attr_e( 'Clear category filter', 'erh' ); ?>" id="comparison-category-clear">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3">
                                <line x1="18" y1="6" x2="6" y2="18"></line>
                                <line x1="6" y1="6" x2="18" y2="18"></line>
                            </svg>
                        </button>
                    </div>
                </header>

                <!-- Screen reader announcements -->
                <div id="comparison-announcer" class="sr-only" aria-live="polite" aria-atomic="true"></div>

                <div class="comparison-row-main" id="comparison-container" data-json-url="<?php echo esc_url( $json_url ); ?>">
                    <!-- Left column: first product -->
                    <div class="comparison-column-left">
                        <div class="comparison-input-wrapper">
                            <input type="text" class="comparison-input" placeholder="<?php esc_attr_e( 'Search products...', 'erh' ); ?>" autocomplete="off" data-slot="0">
                            <button type="button" class="comparison-input-clear" aria-label="<?php esc_attr_e( 'Clear selection', 'erh' ); ?>">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <line x1="18" y1="6" x2="6" y2="18"></line>
                                    <line x1="6" y1="6" x2="18" y2="18"></line>
                                </svg>
                            </button>
                            <img class="comparison-input-thumb" src="" alt="" aria-hidden="true">
                            <div class="comparison-results"></div>
                        </div>
                    </div>

                    <!-- VS divider -->
                    <span class="comparison-vs"><?php esc_html_e( 'vs', 'erh' ); ?></span>

                    <!-- Right column: second product + dynamic additions -->
                    <div class="comparison-column-right" id="comparison-right-column">
                        <div class="comparison-input-wrapper">
                            <input type="text" class="comparison-input" placeholder="<?php esc_attr_e( 'Search products...', 'erh' ); ?>" autocomplete="off" data-slot="1">
                            <button type="button" class="comparison-input-clear" aria-label="<?php esc_attr_e( 'Clear selection', 'erh' ); ?>">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <line x1="18" y1="6" x2="6" y2="18"></line>
                                    <line x1="6" y1="6" x2="18" y2="18"></line>
                                </svg>
                            </button>
                            <img class="comparison-input-thumb" src="" alt="" aria-hidden="true">
                            <div class="comparison-results"></div>
                        </div>
                    </div>

                    <!-- Compare button -->
                    <div class="comparison-actions">
                        <button type="button" class="comparison-btn" id="comparison-submit" disabled>
                            <?php esc_html_e( 'Compare', 'erh' ); ?>
                            <?php echo erh_icon( 'arrow-right', 'icon' ); ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
